# Generated by Django 5.2.5 on 2025-08-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('agent', 'Agent'), ('hotel_manager', 'Hotel Manager'), ('admin', 'Administrator')], default='buyer', max_length=20, verbose_name='user type'),
        ),
    ]
